### ISSUE TITLE
Popover doesn't appear in Firefox.

### ISSUE THREAD

**Issue by marko-hologram** [juliankrispel/react-text-selection-popover#11] opened 2018-07-30 09:42 UTC
Hello,

I tried your [codesandbox example](https://codesandbox.io/s/github/juliankrispel/react-text-selection-popover/tree/master/example) and it doesn't work in Firefox. Tested on Firefox 61.0.1 and Firefox Developer Edition 62.0b12 on Windows 10 (v1803).

It works in Chrome Version 68.0.3440.75 and Microsoft Edge 17 on the same machine.

Only one error appears in console: "Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `_class`, expected `function`."

Error appears in all browsers, but popover still works in those mentioned so I'm not sure if that error is really related to the problem somehow.

**Comment by juliankrispel** [comment] 2018-07-30 21:25
@marko-hologram thanks for this! On it

**Comment by juliankrispel** [comment] 2018-07-30 21:50
I just tested on `60` on osx and it seems to work

**Comment by juliankrispel** [comment] 2018-07-30 22:07
@marko-hologram I've tried this in firefox on windows and osx and it works.

Here's firefox for osx:

![image](https://user-images.githubusercontent.com/1188186/43426312-314d949e-944d-11e8-8f2f-30dd0e026edc.png)

**Comment by juliankrispel** [comment] 2018-07-30 22:11
and here it is on windows:

![image](https://user-images.githubusercontent.com/1188186/43426530-dbcb6752-944d-11e8-8e35-d1e9e2b85832.png)

**Comment by juliankrispel** [comment] 2018-07-30 22:20
I'll close this for now since I can't find a way to reproduce it. If you can please do let me know and we'll see to fixing it!

**Closed as completed** 2018-07-30 22:21 UTC

**Comment by marko-hologram** [comment] 2018-07-31 04:53
@juliankrispel I just tested it on my personal machine on windows 10 and it works, same version of Firefox. The first machine I tested was my work PC. Strange.

I guess it's just something totally unrelated to your code. Sorry for the false alarm.
